### PR TITLE
Face recognition initial PR

### PR DESCRIPTION
**Pull request by iasonth95**
This is the new pkg of face recognition using openface neural network for face detection and recognition. 
This is an initial PR checking.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
I updated this branch. I renamed the the package to include the `image_recognition` prefix. Your recent changes apply to the pkg with prefix. So please reset this branch to 65d24ed3fd40b790924105abecf8e9940d874504 and cherry-pick 6c993189f082a95e0397339f3af6e7571a800be0 on top of that. The other merge commits shouldn't be necessary.

**Comment by iasonth95** [comment]
will do that today

**Comment by MatthijsBurgh** [comment]
Can you remove as possible unnecessary files/code/text etc. Once this is as clean as possible, doesn't need to work yet. We can at least merge some stuff to master. And then work on the implementation. Which we have the first version of on the other branch.

**Comment by MatthijsBurgh** [comment]
Merging this one, so there is something on master. And we can develop.

**Pull request merged**
