### PR TITLE
Fix/remove dependencies that are not in rosdep

### PR DESCRIPTION
**Pull request by Rayman**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@Rayman are you adding these to the install.yaml?

**Comment by reinzor** [comment]
Where are the others used in the code? TF is indeed used but can also be installed via another way. Don't know the best approach for this.

**Comment by reinzor** [comment]
Where us six used?

**Comment by MatthijsBurgh** [comment]
https://github.com/tue-robotics/image_recognition/blob/master/tensorflow_ros/src/tensorflow_ros/utils.py#L3
https://github.com/tue-robotics/image_recognition/blob/master/tensorflow_ros/src/tensorflow_ros/tf_retrain.py#L77

**Pull request merged**
