### PR TITLE
Openpose python and linting

### PR DESCRIPTION
**Pull request by reinzor**
Openpose python wrapper use and added linting

### CODE REVIEW

**Comment by reinzor** [comment]
Travis is failing for some reason, please re-trigger travis and review

**Comment by MatthijsBurgh** [comment]
travis:
`The command "sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin" failed and exited with 100 during .`

**Comment by ar13pit** [comment]
@MatthijsBurgh Wouldn't it be better to update .travis.yml with TUE image like the other packages? It currently uses Ubuntu 14.04 and ROS Indigo here.

**Comment by reinzor** [comment]
I don't want these packages to be dependent on tue specific ci. An issue
could be created for adding kinetic / melodic ci.

**Comment by reinzor** [comment]
CI updated to industrial CI

**Pull request merged**
