### PR TITLE
Feature/augmentation flags

### PR DESCRIPTION
**Pull request by LoyVanBeek**

### CODE REVIEW

**Comment by reinzor** [comment]
@LoyVanBeek and @MatthijsBurgh did you both test this? If so, then it's fine with me

**Comment by MatthijsBurgh** [comment]
I have tested it. @LoyVanBeek, could you test it once more, because I am the last editor.
To test via command line: retrain with extra argument ```--architecture=mobilenet_1.0_224```
Mobilenet networks can't be used for inference yet.
To test via GUI: rosrun tensorflow_ros_rqt train_gui

**Comment by LoyVanBeek** [comment]
Which version of Tensorflow is this for? Do we all need to upgrade?

```bash
rosrun tensorflow_ros_rqt train_gui
```
results in 
```
RosPluginProvider.load(tensorflow_ros_rqt/Tensorflow Train Plugin) exception raised in __builtin__.__import__(tensorflow_ros_rqt.train, [TrainPlugin]):
Traceback (most recent call last):
...
  File "/home/loy/ros/kinetic/system/src/tensorflow_ros/src/tensorflow_ros/tf_retrain.py", line 117, in <module>
    from tensorflow.contrib.quantize.python import quant_ops
ImportError: No module named quantize.python

PluginManager._load_plugin() could not load plugin "tensorflow_ros_rqt/Tensorflow Train Plugin":
...
ImportError: No module named quantize.python
```

**Comment by LoyVanBeek** [comment]
Given your on the latest TF version, things don't blow up. 
Running both 
```bash
rosrun tensorflow_ros_rqt train_gui #click "Train ...."
```

and e.g. 
```bash
rosrun tensorflow_ros retrain ~/MEGA/data/robotics_testlabs/training_data_Josja/training /tmp/inception /tmp/dummy  --batch=100 --steps=10 --random_brightness=10 --architecture=mobilenet_1.0_224
```

both run without errors.

**Comment by MatthijsBurgh** [comment]
@LoyVanBeek so approved??

**Pull request merged**
