### PR TITLE
Test for face_properties with keras

### PR DESCRIPTION
**Pull request by reinzor**
Will download the model and run tests based on the GT images in the assets folder

### CODE REVIEW

**Comment by reinzor** [comment]
Why not correct?

**Comment by LoyVanBeek** [comment]
She's not 28...

**Comment by reinzor** [comment]
@LoyVanBeek , could you review?

**Comment by reinzor** [comment]
Good call, maybe host the network in a github release of this repo?

**Comment by LoyVanBeek** [comment]
Yes, that's how this is commonly done. The network is [MIT licenced](https://github.com/yu4u/age-gender-estimation/blob/master/LICENSE) so we have to add that as well, I think.

**Pull request merged**
