### PR TITLE
Refactor/image recognition prefix

### PR DESCRIPTION
**Pull request by reinzor**

### CODE REVIEW

**Comment by reinzor** [comment]
This can be merged IMO if we update the launch files that depend on this ..

**Comment by MatthijsBurgh** [comment]
Changes in bringup packages have been added to robocup branches. Other packages, see PR's

**Comment by reinzor** [comment]
Thanks, so this can be merged?

**Comment by reinzor** [comment]
If so, please approve so that I can merge :)

**Comment by MatthijsBurgh** [comment]
If you approve the other ones, I will approve this one and merge them al tonight

**Pull request merged**
